"""Initial migration with all tables

Revision ID: 79c3cf47db92
Revises: 
Create Date: 2026-03-18 08:35:28.700879+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c3cf47db92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('career_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_categories_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_career_categories_id'), ['id'], unique=False)

    op.create_table('career_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('career_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_skills_id'), ['id'], unique=False)

    op.create_table('interview_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('technology_field', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('is_realtime', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_scenarios_id'), ['id'], unique=False)

    op.create_table('job_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('api_endpoint', sa.String(length=500), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('job_platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_platforms_id'), ['id'], unique=False)

    op.create_table('major_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('major_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_major_categories_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_major_categories_id'), ['id'], unique=False)

    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('resource_type', sa.Enum('question', 'course', 'video', name='resourcetype'), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('duration_or_quantity', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('completions', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_resource_type'), ['resource_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('wechat_open_id', sa.String(length=28), nullable=True),
    sa.Column('wechat_union_id', sa.String(length=29), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('gender', sa.Enum('M', 'F', 'O', name='gender'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=False),
    sa.Column('university', sa.String(length=100), nullable=False),
    sa.Column('learning_stage', sa.Enum('FRESHMAN_1', 'FRESHMAN_2', 'SOPHOMORE_1', 'SOPHOMORE_2', 'JUNIOR_1', 'JUNIOR_2', 'SENIOR_1', 'SENIOR_2', 'GRADUATE_STUDENT', 'JOB_SEEKER', 'EMPLOYED', 'OTHER', name='learningstage'), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('ethnicity', sa.String(length=50), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('interviewer_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_wechat_open_id'), ['wechat_open_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_wechat_union_id'), ['wechat_union_id'], unique=True)

    op.create_table('careers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('salary_range_min', sa.Integer(), nullable=True),
    sa.Column('salary_range_max', sa.Integer(), nullable=True),
    sa.Column('growth_path', sa.Text(), nullable=True),
    sa.Column('work_environment', sa.Text(), nullable=True),
    sa.Column('education_requirement', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['career_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('careers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_careers_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_careers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_careers_name'), ['name'], unique=False)

    op.create_table('external_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_months', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('education_requirement', sa.String(length=50), nullable=True),
    sa.Column('experience_requirement', sa.String(length=50), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('job_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('skills_required', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['job_platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'external_id', name='uq_platform_external_job')
    )
    with op.batch_alter_table('external_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_jobs_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_jobs_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_jobs_platform_id'), ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_jobs_title'), ['title'], unique=False)

    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('created', 'in_progress', 'paused', 'completed', 'cancelled', 'expired', name='interviewsessionstatus'), nullable=False),
    sa.Column('_scenario_description_cache', sa.String(length=500), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['interview_scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('lc_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pass_rate', sa.String(length=20), nullable=False),
    sa.Column('solution_url', sa.String(length=500), nullable=False),
    sa.Column('question_url', sa.String(length=500), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'resource_id', name='uq_lc_question_resource')
    )
    with op.batch_alter_table('lc_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lc_questions_id'), ['id'], unique=False)

    op.create_table('major_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['major_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('major_subcategories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_major_subcategories_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_major_subcategories_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_major_subcategories_id'), ['id'], unique=False)

    op.create_table('resume_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_score', sa.String(length=100), nullable=False),
    sa.Column('resume_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('resume_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_evaluations_id'), ['id'], unique=False)

    op.create_table('user_career_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_careers', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('preferred_cities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('salary_expectation_min', sa.Integer(), nullable=True),
    sa.Column('salary_expectation_max', sa.Integer(), nullable=True),
    sa.Column('work_preference', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_career_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_career_preferences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_career_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('user_resource_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_resource_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_resource_interactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_resource_interactions_interaction_type'), ['interaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_resource_interactions_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_resource_interactions_user_id'), ['user_id'], unique=False)

    op.create_table('career_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('target_career_id', sa.Integer(), nullable=True),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('target_stage', sa.String(length=50), nullable=True),
    sa.Column('timeline_months', sa.Integer(), nullable=True),
    sa.Column('milestones', sa.JSON(), nullable=True),
    sa.Column('skills_gap', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('learning_resources', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('ai_suggestions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_career_id'], ['careers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('career_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_plans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_career_plans_user_id'), ['user_id'], unique=False)

    op.create_table('career_skill_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['career_skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'skill_id', name='uq_career_skill')
    )
    with op.batch_alter_table('career_skill_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_skill_mappings_career_id'), ['career_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_career_skill_mappings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_career_skill_mappings_skill_id'), ['skill_id'], unique=False)

    op.create_table('interview_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_questions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_questions_session_id'), ['session_id'], unique=False)

    op.create_table('job_career_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['external_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'career_id', name='uq_job_career')
    )
    with op.batch_alter_table('job_career_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_career_mappings_career_id'), ['career_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_career_mappings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_career_mappings_job_id'), ['job_id'], unique=False)

    op.create_table('majors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('degree_type', sa.String(length=20), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subcategory_id'], ['major_subcategories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('majors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_majors_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_majors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_majors_subcategory_id'), ['subcategory_id'], unique=False)

    op.create_table('overall_interview_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('overall_evaluation', sa.Text(), nullable=False),
    sa.Column('help', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('professional_knowledge', sa.Integer(), nullable=False),
    sa.Column('skill_match', sa.Integer(), nullable=False),
    sa.Column('language_expression', sa.Integer(), nullable=False),
    sa.Column('logical_thinking', sa.Integer(), nullable=False),
    sa.Column('stress_response', sa.Integer(), nullable=False),
    sa.Column('personality', sa.Integer(), nullable=False),
    sa.Column('motivation', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('overall_interview_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_overall_interview_evaluations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_overall_interview_evaluations_user_id'), ['user_id'], unique=False)

    op.create_table('major_career_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('major_id', 'career_id', name='uq_major_career')
    )
    with op.batch_alter_table('major_career_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_major_career_mappings_career_id'), ['career_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_major_career_mappings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_major_career_mappings_major_id'), ['major_id'], unique=False)

    op.create_table('response_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('audio_duration', sa.Float(), nullable=True),
    sa.Column('video_duration', sa.Float(), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    with op.batch_alter_table('response_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_metadata_id'), ['id'], unique=False)

    op.create_table('response_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metadata_id', sa.Integer(), nullable=False),
    sa.Column('speech_text', sa.Text(), nullable=False),
    sa.Column('facial_expression', sa.Text(), nullable=False),
    sa.Column('body_language', sa.Text(), nullable=False),
    sa.Column('analysis_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['metadata_id'], ['response_metadata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metadata_id')
    )
    with op.batch_alter_table('response_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_analysis_id'), ['id'], unique=False)

    op.create_table('answer_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_text', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['response_analysis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_evaluations_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_evaluations_id'))

    op.drop_table('answer_evaluations')
    with op.batch_alter_table('response_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_analysis_id'))

    op.drop_table('response_analysis')
    with op.batch_alter_table('response_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_metadata_id'))

    op.drop_table('response_metadata')
    with op.batch_alter_table('major_career_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_major_career_mappings_major_id'))
        batch_op.drop_index(batch_op.f('ix_major_career_mappings_id'))
        batch_op.drop_index(batch_op.f('ix_major_career_mappings_career_id'))

    op.drop_table('major_career_mappings')
    with op.batch_alter_table('overall_interview_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_overall_interview_evaluations_user_id'))
        batch_op.drop_index(batch_op.f('ix_overall_interview_evaluations_id'))

    op.drop_table('overall_interview_evaluations')
    with op.batch_alter_table('majors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_majors_subcategory_id'))
        batch_op.drop_index(batch_op.f('ix_majors_id'))
        batch_op.drop_index(batch_op.f('ix_majors_code'))

    op.drop_table('majors')
    with op.batch_alter_table('job_career_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_career_mappings_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_career_mappings_id'))
        batch_op.drop_index(batch_op.f('ix_job_career_mappings_career_id'))

    op.drop_table('job_career_mappings')
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_questions_session_id'))
        batch_op.drop_index(batch_op.f('ix_interview_questions_id'))

    op.drop_table('interview_questions')
    with op.batch_alter_table('career_skill_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_skill_mappings_skill_id'))
        batch_op.drop_index(batch_op.f('ix_career_skill_mappings_id'))
        batch_op.drop_index(batch_op.f('ix_career_skill_mappings_career_id'))

    op.drop_table('career_skill_mappings')
    with op.batch_alter_table('career_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_career_plans_id'))

    op.drop_table('career_plans')
    with op.batch_alter_table('user_resource_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_resource_interactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_resource_interactions_resource_id'))
        batch_op.drop_index(batch_op.f('ix_user_resource_interactions_interaction_type'))
        batch_op.drop_index(batch_op.f('ix_user_resource_interactions_id'))

    op.drop_table('user_resource_interactions')
    with op.batch_alter_table('user_career_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_career_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_career_preferences_id'))

    op.drop_table('user_career_preferences')
    with op.batch_alter_table('resume_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_evaluations_id'))

    op.drop_table('resume_evaluations')
    with op.batch_alter_table('major_subcategories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_major_subcategories_id'))
        batch_op.drop_index(batch_op.f('ix_major_subcategories_code'))
        batch_op.drop_index(batch_op.f('ix_major_subcategories_category_id'))

    op.drop_table('major_subcategories')
    with op.batch_alter_table('lc_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lc_questions_id'))

    op.drop_table('lc_questions')
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_interview_sessions_id'))

    op.drop_table('interview_sessions')
    with op.batch_alter_table('external_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_jobs_title'))
        batch_op.drop_index(batch_op.f('ix_external_jobs_platform_id'))
        batch_op.drop_index(batch_op.f('ix_external_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_external_jobs_company_name'))
        batch_op.drop_index(batch_op.f('ix_external_jobs_city'))

    op.drop_table('external_jobs')
    with op.batch_alter_table('careers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_careers_name'))
        batch_op.drop_index(batch_op.f('ix_careers_id'))
        batch_op.drop_index(batch_op.f('ix_careers_category_id'))

    op.drop_table('careers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_wechat_union_id'))
        batch_op.drop_index(batch_op.f('ix_users_wechat_open_id'))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_resource_type'))
        batch_op.drop_index(batch_op.f('ix_resources_id'))

    op.drop_table('resources')
    with op.batch_alter_table('major_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_major_categories_id'))
        batch_op.drop_index(batch_op.f('ix_major_categories_code'))

    op.drop_table('major_categories')
    with op.batch_alter_table('job_platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_platforms_id'))

    op.drop_table('job_platforms')
    with op.batch_alter_table('interview_scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_scenarios_id'))

    op.drop_table('interview_scenarios')
    with op.batch_alter_table('career_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_skills_id'))

    op.drop_table('career_skills')
    with op.batch_alter_table('career_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_categories_id'))
        batch_op.drop_index(batch_op.f('ix_career_categories_code'))

    op.drop_table('career_categories')
    # ### end Alembic commands ###
